services:

  marketplace_product_db:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - ${DB_UI_PORT}:8080

  server:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - ${WEBSERVER_REST_PORT}:8000