services:

  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - HOST=host.docker.internal
      - POSTGRES_PASSWORD=marketplace_product
      - POSTGRES_USER=marketplace_product
      - POSTGRES_DB=marketplace_product

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  server:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - 8000:8000