name: Gofmt

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'

jobs:
  gofmt:
    runs-on: ubuntu-latest
    container: golang:1.21
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Gofmt
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi