name: Gofmt
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'
jobs:
  gofmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Gofmt
        run: |
          files="$(gofmt -s -l .)"
          if [ -n "$files" ]; then
            echo "gofmt found issues in the following files:"
            echo "$files"
            echo
            echo "Remarks:"
            gofmt -w .
            exit 1
          else
             echo "gofmt: no issues found"
          fi